export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";

export const API_FAILED = "AUTH_API_FAILED";

export const UPDATE_CREDITS = "UPDATE_CREDITS";//credits

export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN";

export const REGISTER_VALIDATE = "REGISTER_VALIDATE";

export const REGISTER_INVALID = "REGISTER_INVALID";
export const REGISTER_VALID = "REGISTER_VALID";